INCLUDE(TribitsTplDeclareLibraries)
INCLUDE( ${AMP_SOURCE_DIR}/cmake/macros.cmake )
INCLUDE( ${AMP_SOURCE_DIR}/cmake/FindSundials.cmake )

# Get SUNDIALS_DIRECTORY
IF ( SUNDIALS_DIR )
    SET( SUNDIALS_DIRECTORY ${SUNDIALS_DIR} )
ELSEIF( TPL_SUNDIALS_DIR )
    SET( SUNDIALS_DIRECTORY ${TPL_SUNDIALS_DIR} )
ELSE()
    MESSAGE(FATAL_ERROR "Could not find SUNDIALS.  Please manually set SUNDIALS_DIR or TPL_SUNDIALS_DIR to point to the SUNDIALS installation directory" )
ENDIF()
VERIFY_PATH ( ${SUNDIALS_DIRECTORY} )

# Find the SUNDIALS includes
SUNDIALS_SET_INCLUDES( ${SUNDIALS_DIRECTORY} )

# Find the SUNDIALS libraries
SUNDIALS_SET_LIBRARIES( ${SUNDIALS_DIRECTORY} )
MESSAGE ( "Using SUNDIALS" )
MESSAGE ( "   "  ${SUNDIALS_LIBS} )

# Add the tribits flags
SET( TPL_ENABLE_SUNDIALS ON )
SET( TPL_SUNDIALS_INCLUDE_DIRS ${SUNDIALS_INCLUDE} )
SET( TPL_SUNDIALS_LIBRARY_DIRS "" )
SET( TPL_SUNDIALS_LIBRARIES ${SUNDIALS_LIBS} )
SET( ${SUNDIALS_LIBS} )

# Add the definitions
SET( USE_EXT_SUNDIALS 1 )

