INCLUDE(TribitsTplDeclareLibraries)
INCLUDE( ${AMP_SOURCE_DIR}/cmake/macros.cmake )
INCLUDE( ${AMP_SOURCE_DIR}/cmake/TPLFindPPETSC_AMP.cmake )

# Call the main find Petsc TPL
SET( TPL_ENABLE_PETSC ON )
SET( TPL_PETSC_INCLUDE_DIRS ${TPL_PETSC_AMP_INCLUDE_DIRS} )
SET( TPL_PETSC_LIBRARY_DIRS ${TPL_PETSC_AMP_LIBRARY_DIRS} )
SET( TPL_PETSC_LIBRARIES ${TPL_PETSC_AMP_LIBRARIES} )

