INCLUDE(TribitsTplDeclareLibraries)

IF (NOT TPL_ENABLE_HDF5)
    MESSAGE(FATAL_ERROR "SILO required HDF5") 
ENDIF()

TRIBITS_TPL_DECLARE_LIBRARIES( SILO
    REQUIRED_HEADERS silo.h
    REQUIRED_LIBS_NAMES siloh5
)

MESSAGE ( "Using SILO" )
MESSAGE ( "   "  ${SILO_LIBS} )

# Add the definitions
SET( SILO_LIBS ${TPL_SILO_LIBRARIES} )
SET( TPL_ENABLE_SILO ON )
SET( USE_EXT_SILO 1 )


