INCLUDE(TribitsTplDeclareLibraries)

IF ( NOT DENDRO_DIRECTORY AND TPL_DENDRO_DIR )
    SET( DENDRO_DIRECTORY ${TPL_DENDRO_DIR} )
ENDIF()
IF ( DENDRO_DIRECTORY )
    VERIFY_PATH( ${DENDRO_DIRECTORY} )
    SET( DENDRO_INCLUDE ${DENDRO_DIRECTORY}/include )
    INCLUDE_DIRECTORIES( ${DENDRO_INCLUDE} )
    FIND_LIBRARY( DENDRO_BIN_LIB   NAMES BinOps PATHS ${DENDRO_DIRECTORY}/lib  NO_DEFAULT_PATH )
    FIND_LIBRARY( DENDRO_OCT_LIB   NAMES Oct    PATHS ${DENDRO_DIRECTORY}/lib  NO_DEFAULT_PATH )
    FIND_LIBRARY( DENDRO_PAR_LIB   NAMES Par    PATHS ${DENDRO_DIRECTORY}/lib  NO_DEFAULT_PATH )
    FIND_LIBRARY( DENDRO_POINT_LIB NAMES Point  PATHS ${DENDRO_DIRECTORY}/lib  NO_DEFAULT_PATH )
    FIND_LIBRARY( DENDRO_TEST_LIB  NAMES Test   PATHS ${DENDRO_DIRECTORY}/lib  NO_DEFAULT_PATH )
    IF ( (NOT DENDRO_BIN_LIB) OR (NOT DENDRO_OCT_LIB) OR (NOT DENDRO_PAR_LIB) OR
        (NOT DENDRO_POINT_LIB) OR (NOT DENDRO_TEST_LIB) )
        MESSAGE( ${DENDRO_BIN_LIB} )
        MESSAGE( ${DENDRO_OCT_LIB} )
        MESSAGE( ${DENDRO_PAR_LIB} )
        MESSAGE( ${DENDRO_POINT_LIB} )
        MESSAGE( ${DENDRO_TEST_LIB} )
        MESSAGE( FATAL_ERROR "DENDRO libraries not found in ${DENDRO_DIRECTORY}/lib" )
    ENDIF()
    # Add the libraries in the appropriate order
    SET( DENDRO_LIBS
        ${DENDRO_OCT_LIB}
        ${DENDRO_PAR_LIB}
        ${DENDRO_POINT_LIB}
        ${DENDRO_TEST_LIB}
        ${DENDRO_BIN_LIB}
     )
ELSE()
    MESSAGE( FATAL_ERROR "Default search for DENDRO is not supported.  Use -D DENDRO_DIRECTORY=" )
ENDIF()

MESSAGE( "Using Dendro" )
MESSAGE( "   "  ${DENDRO_LIBS} )

# Add the definitions
SET( TPL_DENDRO_INCLUDE_DIRS ${DENDRO_INCLUDE} )
SET( TPL_DENDRO_LIBRARIES ${DENDRO_LIBS} )
SET( TPL_DENDRO_LIBRARY_DIRS ${DENDRO_DIRECTORY}/lib )
SET( TPL_ENABLE_DENDRO ON )
SET( USE_EXT_DENDRO 1 )




