INCLUDE(TribitsTplDeclareLibraries)

TRIBITS_TPL_DECLARE_LIBRARIES( HDF5
    REQUIRED_HEADERS hdf5.h
    REQUIRED_LIBS_NAMES hdf5
)

IF(TPL_ENABLE_MPI)
    ADD_DEFINITIONS( -DH5_HAVE_PARALLEL )
ENDIF()

MESSAGE ( "Using HDF5" )
MESSAGE ( "   "  ${HDF5_LIBS} )

# Add the definitions
SET( TPL_ENABLE_HDF5 ON )
SET( USE_EXT_HDF5 1 )

