INCLUDE(TribitsTplDeclareLibraries)
INCLUDE( ${AMP_SOURCE_DIR}/cmake/macros.cmake )


# Get X11_DIRECTORY
IF ( X11_DIR )
    SET( X11_DIRECTORY ${X11_DIR} )
ELSEIF( TPL_X11_DIR )
    SET( X11_DIRECTORY ${TPL_X11_DIR} )
ELSE()
    MESSAGE(FATAL_ERROR "Could not find X11.  Please manually set X11_DIR or TPL_X11_DIR to point to the X11 installation directory" )
ENDIF()
VERIFY_PATH ( ${X11_DIRECTORY} )
VERIFY_PATH ( ${X11_DIRECTORY}/include )


# Get the libraries
FIND_LIBRARY ( X11_SM_LIB  NAMES SM  PATHS ${X11_DIRECTORY}/lib  NO_DEFAULT_PATH )
FIND_LIBRARY ( X11_ICE_LIB NAMES ICE PATHS ${X11_DIRECTORY}/lib  NO_DEFAULT_PATH )
FIND_LIBRARY ( X11_X11_LIB NAMES X11 PATHS ${X11_DIRECTORY}/lib  NO_DEFAULT_PATH )
SET( X11_LIBS ${X11_SM_LIB} ${X11_ICE_LIB} ${X11_X11_LIB} )

# Add the tribits flags
SET( TPL_ENABLE_X11_AMP ON )
SET( TPL_X11_INCLUDE_DIRS ${X11_DIRECTORY}/include )
SET( TPL_X11_LIBRARY_DIRS ${X11_DIRECTORY}/lib )
SET( TPL_X11_LIBRARIES ${X11_LIBS} )


# Add the definitions
SET( USE_EXT_PETSC 1 )
MESSAGE ( "Using X11" )
MESSAGE ( "   "  ${TPL_X11_LIBRARIES} )

