INCLUDE(TribitsTplDeclareLibraries)

IF (MSVC AND NOT TPL_LAPACK_LIBRARIES AND CLAPACK_FOUND)
  ADVANCED_SET(TPL_LAPACK_LIBRARIES lapack
      CACHE FILEPATH "Set from MSVC CLAPACK specialization")
ENDIF()

TRIBITS_TPL_DECLARE_LIBRARIES( LAPACK
  REQUIRED_LIBS_NAMES "lapack lapack_win32")

# Add the definitions
SET( USE_EXT_LAPCK 1 )

