SET(LIB_REQUIRED_DEP_PACKAGES AMP_UTILITIES )
SET(LIB_OPTIONAL_DEP_PACKAGES )
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS BOOST )
SET(LIB_OPTIONAL_DEP_TPLS MPI LIBMESH SILO HDF5 DENDRO )
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)

# Add trilinos package dependencies
IF ( Trilinos_PACKAGES_AND_DIRS_AND_CLASSIFICATIONS )
    SET(LIB_OPTIONAL_DEP_PACKAGES ${LIB_OPTIONAL_DEP_PACKAGES} STK )
ENDIF()

