SET(LIB_REQUIRED_DEP_PACKAGES AMP_UTILITIES AMP_DISCRETIZATION)
SET(LIB_OPTIONAL_DEP_PACKAGES AMP_MESH)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS BOOST)
SET(LIB_OPTIONAL_DEP_TPLS MPI PETSC_AMP X11)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)

# Add trilinos package dependencies
IF ( Trilinos_PACKAGES_AND_DIRS_AND_CLASSIFICATIONS )
    SET(LIB_OPTIONAL_DEP_PACKAGES ${LIB_OPTIONAL_DEP_PACKAGES} Epetra Thyra )
ENDIF()

