# Find cppcheck if availible
FIND_PROGRAM( CPPCLEAN
    NAMES cppclean cppclean.exe 
    PATHS "${CPPCLEAN_DIRECTORY}" "C:/Program Files/Cppclean" "C:/Program Files (x86)/Cppclean" 
)
IF ( CPPCHECK )
    MESSAGE(STATUS "Using cppclean")
ELSE()
    MESSAGE(STATUS "cppclean not found")
ENDIF()

# Set the options for cppcheck
IF( NOT DEFINED CPPCLEAN_INCLUDE )
    SET( CPPCLEAN_INCLUDE )
    GET_PROPERTY( dirs DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" PROPERTY INCLUDE_DIRECTORIES )
    FOREACH(dir ${dirs})
        SET( CPPCLEAN_INCLUDE ${CPPCLEAN_INCLUDE} "${dir}" )
    ENDFOREACH()
ENDIF()

# Helper function
FUNCTION( CPPCLEAN_PRINT_VAR FILENAME VAR )
    IF ( CPPCLEAN_${VAR} )
        FILE(APPEND "${FILENAME}" "MESSAGE(STATUS \"${VAR}:\")\n" )
        FILE(APPEND "${FILENAME}" "FOREACH( line \${${VAR}} )\n" )
        FILE(APPEND "${FILENAME}" "   MESSAGE(\${line})\n" )
        FILE(APPEND "${FILENAME}" "ENDFOREACH()\n" )
        FILE(APPEND "${FILENAME}" "MESSAGE(\"\")\n" )
        FILE(APPEND "${FILENAME}" "LIST(LENGTH ${VAR} len)\nMATH(EXPR ERR \"\${ERR}+\${len}\")\n" )
    ENDIF()
ENDFUNCTION()

# Add the test
IF ( CPPCLEAN )
    CHECK_ENABLE_FLAG( CPPCLEAN_UNNECESSARY_INCLUDE 1 )
    CHECK_ENABLE_FLAG( CPPCLEAN_EXTRA_INCLUDE 1 )
    CHECK_ENABLE_FLAG( CPPCLEAN_SHOULD_INCLUDE 1 )
    CHECK_ENABLE_FLAG( CPPCLEAN_INCLUDE_NOT_FOUND 1 )
    CHECK_ENABLE_FLAG( CPPCLEAN_FUN_NOT_FOUND 1 )
    CHECK_ENABLE_FLAG( CPPCLEAN_DECLARED 1 )
    CHECK_ENABLE_FLAG( CPPCLEAN_STATIC 0 )
    CHECK_ENABLE_FLAG( CPPCLEAN_FORWARD_DECLARE 0 )
    CHECK_ENABLE_FLAG( CPPCLEAN_UNUSED_VARIABLE 0 )
    CHECK_ENABLE_FLAG( CPPCLEAN_UNKNOWN 1 )
    # Create a script to run cppclean and check the results
    SET( CPPCLEAN_SOURCE "${CMAKE_CURRENT_SOURCE_DIR}" )
    SET( CPPCLEAN_OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/cppclean/output.txt" )
    SET( CPPCLEAN_ERROR  "${CMAKE_CURRENT_BINARY_DIR}/cppclean/error.txt" )
    SET( FILENAME "${CMAKE_CURRENT_BINARY_DIR}/cppclean/script.cmake" )
    CONFIGURE_FILE( cmake/run.cppclean.template.cmake "${FILENAME}" @ONLY )
    # Create the test
    ADD_TEST( cppclean ${CMAKE_COMMAND} -P "${FILENAME}" )
    SET_TESTS_PROPERTIES( cppclean PROPERTIES PROCESSORS 1 )
ENDIF()

