FUNCTION ( SUNDIALS_SET_INCLUDES  SUNDIALS_DIRECTORY )
    VERIFY_PATH ( ${SUNDIALS_DIRECTORY} )
    VERIFY_PATH ( ${SUNDIALS_DIRECTORY}/include )
    # Include the SUNDIALS directories
    SET ( SUNDIALS_INCLUDE ${SUNDIALS_DIRECTORY}/include )
    SET ( SUNDIALS_INCLUDE ${SUNDIALS_INCLUDE} PARENT_SCOPE )
ENDFUNCTION()


FUNCTION ( SUNDIALS_SET_LIBRARIES  SUNDIALS_DIRECTORY )
    VERIFY_PATH ( ${SUNDIALS_DIRECTORY} )
    VERIFY_PATH ( ${SUNDIALS_DIRECTORY}/lib )
    # Find the SUNDIALS libaries
    FIND_LIBRARY ( SUNDIALS_CVODE_LIB        NAMES  sundials_cvode        PATHS ${SUNDIALS_DIRECTORY}/lib  NO_DEFAULT_PATH )
    FIND_LIBRARY ( SUNDIALS_IDA_LIB          NAMES  sundials_ida          PATHS ${SUNDIALS_DIRECTORY}/lib  NO_DEFAULT_PATH )
    FIND_LIBRARY ( SUNDIALS_IDAS_LIB         NAMES  sundials_idas         PATHS ${SUNDIALS_DIRECTORY}/lib  NO_DEFAULT_PATH )
    FIND_LIBRARY ( SUNDIALS_KINSOL_LIB       NAMES  sundials_kinsol       PATHS ${SUNDIALS_DIRECTORY}/lib  NO_DEFAULT_PATH )
    FIND_LIBRARY ( SUNDIALS_NVECSERIAL_LIB   NAMES  sundials_nvecserial   PATHS ${SUNDIALS_DIRECTORY}/lib  NO_DEFAULT_PATH )
    IF ( (NOT SUNDIALS_CVODE_LIB) OR (NOT SUNDIALS_IDA_LIB) OR (NOT SUNDIALS_IDAS_LIB) OR 
         (NOT SUNDIALS_KINSOL_LIB) OR (NOT SUNDIALS_NVECSERIAL_LIB) )
        MESSAGE ( ${SUNDIALS_CVODE_LIB} )
        MESSAGE ( ${SUNDIALS_IDA_LIB} )
        MESSAGE ( ${SUNDIALS_IDAS_LIB} )
        MESSAGE ( ${SUNDIALS_KINSOL_LIB} )
        MESSAGE ( ${SUNDIALS_NVECSERIAL_LIB} )
        MESSAGE ( FATAL_ERROR "Sundials libraries not found in ${SUNDIALS_DIRECTORY}/lib" )
    ENDIF ()
    IF ( USE_EXT_MPI OR TPL_ENABLE_MPI )
        FIND_LIBRARY ( SUNDIALS_NVECPARALLEL_LIB NAMES  sundials_nvecparallel PATHS ${SUNDIALS_DIRECTORY}/lib  NO_DEFAULT_PATH )
        IF ( NOT SUNDIALS_NVECPARALLEL_LIB )
            MESSAGE ( ${SUNDIALS_NVECPARALLEL_LIB} )
            MESSAGE ( FATAL_ERROR "Sundials libraries not found in ${SUNDIALS_DIRECTORY}/lib" )
        ENDIF ()
    ENDIF ()
    # Add the libraries in the appropriate order
    SET ( SUNDIALS_LIBS
        ${SUNDIALS_CVODE_LIB}
        ${SUNDIALS_IDA_LIB}
        ${SUNDIALS_IDAS_LIB}
        ${SUNDIALS_KINSOL_LIB}
        ${SUNDIALS_NVECPARALLEL_LIB}
        ${SUNDIALS_NVECSERIAL_LIB}
    )
    IF ( USE_EXT_MPI OR TPL_ENABLE_MPI )
        SET ( SUNDIALS_LIBS  ${SUNDIALS_LIBS}  ${SUNDIALS_NVEC_PARALLEL_LIB} )
    ENDIF()
    SET ( SUNDIALS_LIBS ${SUNDIALS_LIBS} PARENT_SCOPE )
ENDFUNCTION()

