FUNCTION ( HYPRE_SET_INCLUDES  HYPRE_DIRECTORY )
    VERIFY_PATH( ${HYPRE_DIRECTORY} )
    VERIFY_PATH( ${HYPRE_DIRECTORY}/include )
    # Include the HYPRE directories
    SET( HYPRE_INCLUDE ${HYPRE_DIRECTORY}/include )
    SET( HYPRE_INCLUDE ${HYPRE_INCLUDE} PARENT_SCOPE )
ENDFUNCTION()


FUNCTION( HYPRE_SET_LIBRARIES  HYPRE_DIRECTORY )
    VERIFY_PATH ( ${HYPRE_DIRECTORY} )
    VERIFY_PATH ( ${HYPRE_DIRECTORY}/lib )
    SET( HYPRE_LIB_DIRECTORY ${HYPRE_DIRECTORY}/lib )
    # Find the HYPRE libaries
    SET( HYPRE_LIB_DIRECTORY ${HYPRE_DIRECTORY}/lib )
    FIND_LIBRARY ( HYPRE_LIB         NAMES HYPRE                PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_DM_LIB      NAMES HYPRE_DistributedMatrix  PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_DMPS_LIB    NAMES HYPRE_DistributedMatrixPilutSolver  PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_IJMV_LIB    NAMES HYPRE_IJ_mv          PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_KRYLOV_LIB  NAMES HYPRE_krylov         PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_MATMAT_LIB  NAMES HYPRE_MatrixMatrix   PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_MULTIV_LIB  NAMES HYPRE_multivector    PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_PARAS_LIB   NAMES HYPRE_ParaSails      PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_PBMV_LIB    NAMES HYPRE_parcsr_block_mv  PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_PLS_LIB     NAMES HYPRE_parcsr_ls      PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_PMV_LIB     NAMES HYPRE_parcsr_mv      PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_SEQMV_LIB   NAMES HYPRE_seq_mv         PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_SSLS_LIB    NAMES HYPRE_sstruct_ls     PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_SSMV_LIB    NAMES HYPRE_sstruct_mv     PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_SLS_LIB     NAMES HYPRE_struct_ls      PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_SMV_LIB     NAMES HYPRE_struct_mv      PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    FIND_LIBRARY ( HYPRE_UTIL_LIB    NAMES HYPRE_utilities      PATHS ${HYPRE_LIB_DIRECTORY}  NO_DEFAULT_PATH )
    IF ( NOT HYPRE_LIB )
        MESSAGE( FATAL_ERROR "hypre libraries not found" )
    ENDIF()
    SET ( HYPRE_LIBS )
    IF ( HYPRE_DM_LIB )
        SET ( HYPRE_LIBS ${HYPRE_LIBS}
            ${HYPRE_DM_LIB}
            ${HYPRE_DMPS_LIB}
            ${HYPRE_IJMV_LIB}
            ${HYPRE_KRYLOV_LIB}
            ${HYPRE_MATMAT_LIB}
            ${HYPRE_MULTIV_LIB}
            ${HYPRE_PARAS_LIB}
            ${HYPRE_PBMV_LIB}
            ${HYPRE_PLS_LIB}
            ${HYPRE_PMV_LIB}
            ${HYPRE_SEQMV_LIB}
            ${HYPRE_SSLS_LIB}
            ${HYPRE_SSMV_LIB}
            ${HYPRE_SLS_LIB}
            ${HYPRE_SMV_LIB}
            ${HYPRE_UTIL_LIB}
        )
    ENDIF()
    SET ( HYPRE_LIBS ${HYPRE_LIBS} ${HYPRE_LIB} )
    SET ( HYPRE_LIBS ${HYPRE_LIBS} PARENT_SCOPE )
ENDFUNCTION()

