SET(LIB_REQUIRED_DEP_PACKAGES AMP_UTILITIES AMP_MESH AMP_DISCRETIZATION AMP_VECTORS AMP_MATRICES AMP_OPERATORS )
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS BOOST)
SET(LIB_OPTIONAL_DEP_TPLS MPI PETSC_AMP X11)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)


